### ISSUE TITLE
Fix ibid. citations

### ISSUE THREAD

**Issue by lgienapp** [langsci/194#3]
As of now, all "ibid." citations are written in plain text instead of macros. Change to appropriate citations to get consistent page number styling etc.
Whats the general stance ibid.? Keep them as ibid. or change to "full" citations?

All occurrences are marked with Todo-Labels in the PDF.

**Comment by lgienapp** [comment]
If they should be kept as "ibid." - what are the appropriate macros with biblatex-sp-unified?

**Comment by czulo** [comment]
Überall ersetzt mit kompletten Verweisen.

**Comment by czulo** [comment]
Please close @lgienapp , I cannot close

**Comment by lgienapp** [comment]
Fixed by aad5549c2f1eaa0e86c7c2e2845bf3ee7eb0bf79
